Add env_prefix "" support to EJSON
palkan/anyway_config pull request #126
Opened 2023-04-04 16:55 UTC by bessey

## What is the purpose of this pull request?

Ensures that EJSON, like the ENV and Doppler loaders, supports not utilising the namespaced configuration feature. 

Happy to follow up with tests and docs if you think this is reasonable!

## Is there anything you'd like reviewers to focus on?

To keep the API surface small I have used the `env_prefix` keyword, even though its not really a prefix in this context (JSON nested keys). I figure consistency is preferable.

## Checklist

- [ ] I've added tests for this change
- [ ] I've added a Changelog entry
- [ ] I've updated a documentation

2023-04-05 01:45 UTC, palkan commented
Thanks for the proposal!

Agree, it makes. Though I'm not sure `env_prefix` is the right way to handle this.

I think, we should introduce an API to pass custom options to loaders. Smth like:

```ruby
class MyConfig < Anyway::Config
  loader_options ejson_prefix: "" 
end
```

2023-04-05 13:45 UTC, bessey commented
Hey @palkan, yeah I prefer that, certainly more modular for those adding their own loaders.

I went with `ejson_namespace` as I felt "namespace" more accurately describes the concept in JSON. "prefix" makes sense when its string concatenation, but here we are nesting JSON blobs within X. X = a namespace.

Introduced some low level tests but I wasn't sure how best to write tests for Config since right now only the EJSON loader uses this functionality.

I also used `nil` to signify "no namespace" but I think perhaps `false` would be a better option actually. I know prefix uses `""` but again, that doesn't seem appropriate in this context to me. Its a small change though so if that consistency is preferred, its easily done.

If you want to take this PR over at this point, feel free to make your own changes.

2023-04-05 22:23 UTC, palkan requested changes
Thanks! LGTM.

Please, take a look at the comments and CI failures.

2023-04-05 22:23 UTC, palkan commented on spec/loaders/ejson_spec.rb
> +        # It also includes the public key, but we don't care about it
Maybe, it makes sense to remove "_public_key" from the resulting hash to avoid it's potential leakage?

2023-04-05 22:23 UTC, palkan commented on lib/anyway/config.rb
> +        @loader_options = {}
I think, we also need to take care of inheritance (see other class-level configuration methods)

2023-04-05 22:23 UTC, palkan commented on lib/anyway/loaders/ejson.rb
> +          config_hash = if ejson_namespace.nil?
> I think perhaps false would be a better option actually. 

Agree, `false` sounds better. Let's just replace the check with `unless ejson_namespace` to handle both `nil` and `false`

2023-04-11 10:15 UTC, bessey commented
All changes made and hopefully CI passes now (I don't have JRuby to test against so somewhat coding blind there)

2023-04-11 20:36 UTC, palkan commented
Thanks! I'll take care of linting issues.

2023-04-11 20:36 UTC, merged