feature: added suppress_required_validations option
palkan/anyway_config pull request #152
Opened 2024-05-30 17:42 UTC by OlegChuev

## What is the purpose of this pull request?

Closes https://github.com/palkan/anyway_config/issues/151

## What changes did you make? (overview)

Added `suppress_required_validations` configuration for skipping validation in CI:
  - Support for the Rails built-in environment variable `SECRET_KEY_BASE_DUMMY`. If this variable is set, all validations for required attributes are skipped. This is particularly useful for executing `bundle exec rails assets:precompile` in CI/CD pipelines.
  
  - Introduced a global setting `Anyway::Settings.suppress_required_validations = true` to disable validations. This can be toggled via the environment variable `ANYWAY_SUPPRESS_VALIDATIONS`.

  - For Rails applications, `suppress_required_validations` is automatically set to `true` if `SECRET_KEY_BASE_DUMMY` is defined.

## Is there anything you'd like reviewers to focus on?

## Checklist

- [x] I've added tests for this change
- [x] I've added a Changelog entry
- [x] I've updated a documentation

2024-05-30 21:21 UTC, palkan requested changes
Thanks!

Left some comments/suggestions.

2024-05-30 21:21 UTC, palkan commented on CHANGELOG.md
> +## 2.6.5 (2024-05-30)
Please, do not update version numbers/dates; it's only done on release

2024-05-30 21:21 UTC, palkan commented on README.md
> +- [Anyway Config](#anyway-config)
This change is irrelevant and not needed; please, revert.

2024-05-30 21:21 UTC, palkan commented on lib/anyway/rails/settings.rb
> +    self.suppress_required_validations = ENV["SECRET_KEY_BASE_DUMMY"]
Anyway-specific env var must have precedence:

```suggestion
    self.suppress_required_validations = !!ENV["SECRET_KEY_BASE_DUMMY"] unless ENV.key?("ANYWAY_SUPPRESS_VALIDATIONS")
```

2024-05-30 21:21 UTC, palkan commented on lib/anyway/settings.rb
> +    self.suppress_required_validations = ENV["ANYWAY_SUPPRESS_VALIDATIONS"]
Let's be more specific here:

```suggestion
    self.suppress_required_validations = %w[1 t true y yes].include?(ENV["ANYWAY_SUPPRESS_VALIDATIONS"])
```

2024-05-30 21:21 UTC, palkan commented on sig/anyway_config.rbs
> +    def self.suppress_required_validations: -> bool?
It's either true or false

```suggestion
    def self.suppress_required_validations: -> bool
```

2024-05-30 21:21 UTC, palkan commented on spec/config_spec.rb
> +          with_env("ANYWAY_SUPPRESS_VALIDATIONS" => "1") do
We should add another test case with the falsey value (e.g., "ANYWAY_SUPPRESS_VALIDATIONS=0").

2024-12-23 08:39 UTC, david-uhlig commented
@OlegChuev are you still working on this? This change would be most beneficial for using Anyway Config in combination with Kamal. Appreciate your effort!

2025-02-12 02:25 UTC, palkan commented on lib/anyway/rails/settings.rb
> +    self.suppress_required_validations = !!ENV["SECRET_KEY_BASE_DUMMY"] unless ENV.key?("ANYWAY_SUPPRESS_VALIDATIONS")
```suggestion
    self.suppress_required_validations = ENV.key?("SECRET_KEY_BASE_DUMMY") unless ENV.key?("ANYWAY_SUPPRESS_VALIDATIONS")
```

2025-02-12 02:25 UTC, palkan commented
@OlegChuev Thanks! Merging 🚀

2025-02-12 02:25 UTC, merged